#!/usr/bin/env bash
#
# Provision a free-tier EC2 box to run the mobile-agent backend, reachable
# from your phone over Tailscale.
#
# Target: Ubuntu 22.04/24.04 LTS on t2.micro or t3.micro (1 GB RAM).
# Run ON the instance, as the default 'ubuntu' user:
#
#   curl -fsSL <raw-url-of-this-file> -o provision.sh && bash provision.sh
#
# or, if you cloned the repo already:  bash scripts/provision_ec2.sh
#
# Idempotent — safe to re-run.
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/vedhakoushik/mobile-agent.git}"
APP_DIR="${APP_DIR:-$HOME/mobile-agent}"
SERVICE_NAME="mobile-agent"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

# ── 1. Swap ───────────────────────────────────────────────────────────────
# Not optional on 1 GB: chromadb pulls large native wheels (onnxruntime,
# tokenizers) and pip gets OOM-killed mid-install without it. The failure is
# confusing when it happens ("Killed", no traceback), so do it up front.
if ! swapon --show | grep -q '/swapfile'; then
  log "Creating 2 GB swap (pip needs it on a 1 GB box)"
  sudo fallocate -l 2G /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile
  sudo swapon /swapfile
  echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
else
  log "Swap already present — skipping"
fi

# ── 2. System packages ────────────────────────────────────────────────────
log "Installing system packages"
sudo apt-get update -qq
sudo apt-get install -y -qq python3-venv python3-pip git curl

# ── 3. Code ───────────────────────────────────────────────────────────────
if [ -d "$APP_DIR/.git" ]; then
  log "Updating existing checkout at $APP_DIR"
  git -C "$APP_DIR" pull --ff-only
else
  log "Cloning $REPO_URL"
  git clone --depth 1 "$REPO_URL" "$APP_DIR"
fi

# ── 4. Python environment ─────────────────────────────────────────────────
log "Setting up the virtualenv (this is the slow part — several minutes)"
python3 -m venv "$APP_DIR/backend/venv"
"$APP_DIR/backend/venv/bin/pip" install --quiet --upgrade pip
"$APP_DIR/backend/venv/bin/pip" install --quiet -r "$APP_DIR/backend/requirements.txt"

# ── 5. Config ─────────────────────────────────────────────────────────────
# Never overwrite an existing .env — it holds the API key the phone is
# already configured with, plus your LLM provider key.
if [ ! -f "$APP_DIR/.env" ]; then
  log "Writing a starter .env (edit it before starting the service)"
  API_KEY="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
  cat > "$APP_DIR/.env" <<EOF
# Generated by provision_ec2.sh — put this same API_KEY in the phone app.
API_KEY=$API_KEY

LLM_PROVIDER=gemini
GEMINI_API_KEY=

# Neo4j is intentionally not installed here: the navigation graph is
# optional and fail-soft, and it does not fit alongside everything else in
# 1 GB. The backend logs a warning and carries on without it.

# ChromaDB runs in local (file) mode; no separate service needed for one user.
EOF
  chmod 600 "$APP_DIR/.env"
  echo "    A new API_KEY was generated. Retrieve it with:  grep API_KEY $APP_DIR/.env"
else
  log ".env already exists — leaving it untouched"
fi

# ── 6. Tailscale ──────────────────────────────────────────────────────────
# Keeps the backend off the public internet entirely: no inbound security
# group rules, no TLS certificate, no domain. The phone reaches it over the
# encrypted tailnet instead.
if ! command -v tailscale >/dev/null 2>&1; then
  log "Installing Tailscale"
  curl -fsSL https://tailscale.com/install.sh | sh
else
  log "Tailscale already installed"
fi

# ── 7. systemd service ────────────────────────────────────────────────────
log "Installing the $SERVICE_NAME systemd service"
sudo tee "/etc/systemd/system/$SERVICE_NAME.service" >/dev/null <<EOF
[Unit]
Description=mobile-agent backend
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$APP_DIR
# 0.0.0.0 is safe here *because* nothing is exposed publicly: the EC2
# security group opens no inbound ports, so the only route in is Tailscale.
ExecStart=$APP_DIR/backend/venv/bin/python -m uvicorn backend.api.main:app --host 0.0.0.0 --port 8000
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME" >/dev/null

cat <<EOF

$(printf '\033[1;32m')Provisioning done.$(printf '\033[0m')

Remaining steps (each needs your input, so they are not automated):

  1. Put your LLM key in the config:
         nano $APP_DIR/.env          # set GEMINI_API_KEY=...

  2. Join your tailnet (prints a login URL to open in a browser):
         sudo tailscale up

  3. Start the backend:
         sudo systemctl start $SERVICE_NAME
         systemctl status $SERVICE_NAME --no-pager

  4. Note this machine's tailnet IP — this is what goes in the phone app:
         tailscale ip -4

  5. In the Hey Agent app on your phone:
         Backend URL : http://<that-tailscale-ip>:8000
         API_KEY     : $(grep '^API_KEY=' "$APP_DIR/.env" | cut -d= -f2-)

Useful later:
  journalctl -u $SERVICE_NAME -f      # live logs
  sudo systemctl restart $SERVICE_NAME
EOF
